### PR TITLE
Adding cosmoshub-4 genesis

### PR DESCRIPTION
**Pull request by shahankhatch**

### CODE REVIEW

**Review by ebuchman — APPROVED** [review]
Confirmed this hashes to af1c0206f4b331964e66c481b590e5b592e217f21e159e5594cc160b93dd0401

**Comment by nylira** [comment]
jq -S -c -M '' genesis.cosmoshub-4.json | shasum -a 256
af1c0206f4b331964e66c481b590e5b592e217f21e159e5594cc160b93dd0401  -

**Comment by jackzampolin** [comment]
```
jq -S -c -M '' genesis.cosmoshub-4.json | shasum -a 256
af1c0206f4b331964e66c481b590e5b592e217f21e159e5594cc160b93dd0401  -
```

**Review by jackzampolin — APPROVED** [review]

**Comment by shahankhatch** [comment]
jq -S -c -M '' genesis.cosmoshub-4.json | shasum -a 256
af1c0206f4b331964e66c481b590e5b592e217f21e159e5594cc160b93dd0401  -

**Review by zmanian — APPROVED** [review]

**Review by cwgoes — APPROVED** [review]
ACK

```bash
> jq -S -c -M '' genesis.cosmoshub-4.json | shasum -a 256
af1c0206f4b331964e66c481b590e5b592e217f21e159e5594cc160b93dd0401  -
```

**Pull request merged**
